title: Hmovie
email: linda.lor.904@gmail.com
description: >-
  The largest digital Hmong movie database.

baseurl: ""
production_url: "https://www.hmovie.org"
url: "https://www.hmovie.org"

theme: minima

plugins:
  - jekyll-feed

# Google Analytics 
google_analytics: G-XCK7DWWLFC

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - vendor/
